set_property PACKAGE_PIN R8 [get_ports {d[0]}]
set_property PACKAGE_PIN P8 [get_ports {d[1]}]
set_property PACKAGE_PIN P9 [get_ports {d[2]}]
set_property PACKAGE_PIN R7 [get_ports {d[3]}]
set_property PACKAGE_PIN N7 [get_ports {d[4]}]
set_property PACKAGE_PIN R10 [get_ports {d[5]}]
set_property PACKAGE_PIN P10 [get_ports {d[6]}]
set_property PACKAGE_PIN N8 [get_ports {d[7]}]
set_property PACKAGE_PIN E11 [get_ports Push_button]
set_property PACKAGE_PIN M9 [get_ports e]
set_property PACKAGE_PIN N9 [get_ports rs]
#set_property PACKAGE_PIN M10 [get_ports {RowDataIn[0]}]
#set_property PACKAGE_PIN M11 [get_ports {RowDataIn[1]}]
#set_property PACKAGE_PIN R11 [get_ports {RowDataIn[2]}]
#set_property PACKAGE_PIN P11 [get_ports {RowDataIn[3]}]
#set_property PACKAGE_PIN F14 [get_ports {ColDataOut[0]}]
#set_property PACKAGE_PIN F13 [get_ports {ColDataOut[1]}]
#set_property PACKAGE_PIN F12 [get_ports {ColDataOut[2]}]
#set_property PACKAGE_PIN E13 [get_ports {ColDataOut[3]}]

set_property PACKAGE_PIN F14 [get_ports {RowDataIn[3]}]
set_property PACKAGE_PIN F13 [get_ports {RowDataIn[2]}]
set_property PACKAGE_PIN F12 [get_ports {RowDataIn[1]}]
set_property PACKAGE_PIN E13 [get_ports {RowDataIn[0]}]
set_property PACKAGE_PIN M10 [get_ports {ColDataOut[3]}]
set_property PACKAGE_PIN M11 [get_ports {ColDataOut[2]}]
set_property PACKAGE_PIN R11 [get_ports {ColDataOut[1]}]
set_property PACKAGE_PIN P11 [get_ports {ColDataOut[0]}]

#set_property PACKAGE_PIN L12 [get_ports Clock]
# Set the bank voltage for IO Bank 34 to 3.3V
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 34]]

# Set the bank voltage for IO Bank 35 to 3.3V
set_property IOSTANDARD LVCMOS33 [get_ports -of_objects [get_iobanks 35]]